//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandbox {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sandbox.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A{0} B{1:X} C{2,5}D{2,-5}E{2,+5} F{3,5:D}G{3,-5:D}H{3,+5:D}.
        /// </summary>
        internal static string ComplexBetterFormatString {
            get {
                return ResourceManager.GetString("ComplexBetterFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A{0} B{1:X} C{2,5}D{2,-5}E{2,+5} F{3,5:D}G{3,-5:D}H{3,+5:D}.
        /// </summary>
        internal static string ComplexRegularFormatString {
            get {
                return ResourceManager.GetString("ComplexRegularFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] data {
            get {
                object obj = ResourceManager.GetObject("data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon1 {
            get {
                object obj = ResourceManager.GetObject("Icon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image1 {
            get {
                object obj = ResourceManager.GetObject("Image1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t even need a format specifier.
        /// </summary>
        internal static string JustANormalString {
            get {
                return ResourceManager.GetString("JustANormalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream nano_RIP___Real_World {
            get {
                return ResourceManager.GetStream("nano_RIP___Real_World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A regular {0} format {1} string..
        /// </summary>
        internal static string RegularFormat {
            get {
                return ResourceManager.GetString("RegularFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A{0}.
        /// </summary>
        internal static string SimpleBetterFormatString {
            get {
                return ResourceManager.GetString("SimpleBetterFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A{0}.
        /// </summary>
        internal static string SimpleBetterFormatStringWithTypes {
            get {
                return ResourceManager.GetString("SimpleBetterFormatStringWithTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXTTEXTTEXT.
        /// </summary>
        internal static string TextFile1 {
            get {
                return ResourceManager.GetString("TextFile1", resourceCulture);
            }
        }
    }
}
